In [45]:
import pandas as pd

df = pd.read_csv("demostd.csv")
df
print(df.dtypes)
print(type(df))
print(type(df.dtypes))

id              int64
name              str
department        str
cgpa          float64
age             int64
hobby             str
aim               str
profession        str
isPaid            str
gender            str
city              str
dtype: object
<class 'pandas.DataFrame'>
<class 'pandas.Series'>

In [47]:
df
# df['name']

,id,name,department,cgpa,age,hobby,aim,profession,isPaid,gender,city
0,1,Aarav Sharma,CSE,3.85,20,Cricket,Become a Data Scientist,Data Scientist,Yes,Male,Delhi
1,2,Diya Verma,IT,3.76,21,Reading,Work in AI research,AI Engineer,No,Female,Bengaluru
2,3,Rohan Patel,EEE,3.58,19,Football,Design smart systems,Electrical Engineer,Yes,Male,Ahmedabad
3,4,Sneha Iyer,Civil,3.92,22,Sketching,Become a Structural Engineer,Structural Engineer,Yes,Female,Chennai
4,5,Aditya Roy,ME,3.64,20,Gaming,Start an automobile startup,Mechanical Engineer,No,Male,Kolkata
5,6,Meera Nair,BBA,3.81,21,Dancing,Run a business consultancy,Business Consultant,Yes,Female,Hyderabad
6,7,Krishna Singh,CSE,3.69,19,Chess,Develop cybersecurity tools,Cybersecurity Analyst,No,Male,Patna
7,8,Pooja Reddy,IT,3.88,20,Photography,Build cloud applications,Cloud Engineer,Yes,Female,Pune
8,9,Nikhil Kumar,EEE,3.54,21,Music,Work in renewable energy,Power Systems Engineer,No,Male,Jaipur
9,10,Ananya Das,Civil,3.73,22,Traveling,Work on sustainable infrastructure,Civil Engineer,Yes,Female,Coimbatore
10,11,Harsh Mehta,ME,3.67,20,Swimming,Create smart robotics,Robotics Engineer,No,Male,Surat
11,12,Aisha Khan,BBA,3.95,23,Painting,Become a startup founder,Entrepreneur,Yes,Female,Delhi
12,13,Yash Gupta,CSE,3.78,21,Volleyball,Build software for healthcare,Engineer,Yes,Male,Noida
13,14,Sanvi Joshi,IT,3.90,20,Blogging,Work as a product manager,NaN,Yes,Female,Mumbai
14,15,Arjun Nair,EEE,3.61,22,Running,Work in embedded systems,Embedded Engineer,No,Male,Thiruvananthapuram
15,16,Tanvi Shah,Civil,3.84,21,Hiking,Become a project manager,Construction Manager,Yes,Female,NaN
16,17,Veer Malhotra,ME,3.72,19,Table Tennis,Design eco-friendly machines,Mechanical Design Engineer,No,Male,Chandigarh
17,18,Pragya Sinha,BBA,3.87,22,Reading,Lead a marketing team,Marketing Manager,Yes,Female,Lucknow
18,19,Ritwik Das,CSE,3.70,20,Coding,Become a full-stack developer,Full Stack Developer,Yes,Male,Guwahati
19,20,Mahima Rao,IT,NaN,21,Learning Languages,Work in data analytics,Data Analyst,Yes,Female,Bhubaneswar

In [23]:
# df.head(5)
# Surur diker value dekhay
df.head(2)

,id,name,department,cgpa,age,hobby,aim,profession,isPaid,gender,city
0,1,Aarav Sharma,CSE,3.85,20,Cricket,Become a Data Scientist,Data Scientist,Yes,Male,Delhi
1,2,Diya Verma,IT,3.76,21,Reading,Work in AI research,AI Engineer,No,Female,Bengaluru

In [27]:
# Last diker va;ue dekhay
df.tail(1)

,id,name,department,cgpa,age,hobby,aim,profession,isPaid,gender,city
19,20,Mahima Rao,IT,3.93,21,Learning Languages,Work in data analytics,Data Analyst,Yes,Female,Bhubaneswar

In [33]:
import numpy as np
col = df.columns
print(col)
col_lst = np.array(col)
print(col_lst)

Index(['id', 'name', 'department', 'cgpa', 'age', 'hobby', 'aim', 'profession',
       'isPaid', 'gender', 'city'],
      dtype='str')
['id' 'name' 'department' 'cgpa' 'age' 'hobby' 'aim' 'profession' 'isPaid'
 'gender' 'city']

In [39]:
# index ke array cpnvert
idx = np.array(df.index)
print(idx)
print(idx.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int64

In [54]:
df.info()
# df.sample(5)

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          20 non-null     int64
 1   name        20 non-null     str
 2   department  20 non-null     str
 3   cgpa        19 non-null     float64
 4   age         20 non-null     int64
 5   hobby       20 non-null     str
 6   aim         20 non-null     str
 7   profession  19 non-null     str
 8   isPaid      20 non-null     str
 9   gender      20 non-null     str
 10  city        19 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 1.8 KB

In [58]:
df.describe()

             id       cgpa        age
count  20.00000  19.000000  20.000000
mean   10.50000   3.760000  20.700000
std     5.91608   0.120646   1.128576
min     1.00000   3.540000  19.000000
25%     5.75000   3.680000  20.000000
50%    10.50000   3.760000  21.000000
75%    15.25000   3.860000  21.250000
max    20.00000   3.950000  23.000000

## turning data into dataframe

In [66]:
my_lst = [['opar' , 20] , ['alice' , 25]]
lst_df = pd.DataFrame(my_lst , columns=['name' , 'age'])

my_tpl = (('rijoan', 20), ('alice', 25) , ('bob', 30))
tpl_df = pd.DataFrame(my_tpl , columns=['name' , 'age'])
print(tpl_df)
print("======================")
print(lst_df)

     name  age
0  rijoan   20
1   alice   25
2     bob   30
======================
    name  age
0   opar   20
1  alice   25

In [68]:
my_dct = {
    "name" : ["opar", "alice"],
    "age" : [20, 25]
}
dct_df = pd.DataFrame(my_dct)
dct_df

    name  age
0   opar   20
1  alice   25

In [71]:
# accessing dataframe 
df['name']
# type(df['name'])

0      Aarav Sharma
1        Diya Verma
2       Rohan Patel
3        Sneha Iyer
4        Aditya Roy
5        Meera Nair
6     Krishna Singh
7       Pooja Reddy
8      Nikhil Kumar
9        Ananya Das
10      Harsh Mehta
11       Aisha Khan
12       Yash Gupta
13      Sanvi Joshi
14       Arjun Nair
15       Tanvi Shah
16    Veer Malhotra
17     Pragya Sinha
18       Ritwik Das
19       Mahima Rao
Name: name, dtype: str

In [79]:
# ! df.loc[ind start : idx end , col start : col end]

df.loc[3:7 , ['name' , 'age']]

            name  age
3     Sneha Iyer   22
4     Aditya Roy   20
5     Meera Nair   21
6  Krishna Singh   19
7    Pooja Reddy   20

In [76]:
df.loc[[1,5,9]]

,id,name,department,cgpa,age,hobby,aim,profession,isPaid,gender,city
1,2,Diya Verma,IT,3.76,21,Reading,Work in AI research,AI Engineer,No,Female,Bengaluru
5,6,Meera Nair,BBA,3.81,21,Dancing,Run a business consultancy,Business Consultant,Yes,Female,Hyderabad
9,10,Ananya Das,Civil,3.73,22,Traveling,Work on sustainable infrastructure,Civil Engineer,Yes,Female,Coimbatore